# Generated by tools/gen_tags.nim from ../doc/tags.md. DO NOT EDIT!

import tags

type
  RgcStmt* = enum
    NoStmt
    PassS = (ord(PassTagId), "pass")  ## pass declaration
    ModuleS = (ord(ModuleTagId), "module")  ## module declaration
    StmtsS = (ord(StmtsTagId), "stmts")  ## statement list
    InputS = (ord(InputTagId), "input")  ## pass input declaration
    OutputS = (ord(OutputTagId), "output")  ## pass output declaration
    UseS = (ord(UseTagId), "use")  ## module usage declaration
    ConnectS = (ord(ConnectTagId), "connect")  ## resource connection
    RasterS = (ord(RasterTagId), "raster")  ## raster pass body
    ComputeS = (ord(ComputeTagId), "compute")  ## compute pass body
    CopyS = (ord(CopyTagId), "copy")  ## copy pass body
    ShaderS = (ord(ShaderTagId), "shader")  ## shader binding

proc rawTagIsRgcStmt*(raw: TagEnum): bool {.inline.} =
  raw >= PassTagId and raw <= ShaderTagId

