# Generated by tools/gen_tags.nim from ../doc/tags.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    PassTagId
    ModuleTagId
    StmtsTagId
    InputTagId
    OutputTagId
    UseTagId
    ConnectTagId
    RasterTagId
    ComputeTagId
    CopyTagId
    ShaderTagId
    ImageTagId
    BufferTagId
    DotTagId

const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("pass", 1),
    ("module", 2),
    ("stmts", 3),
    ("input", 4),
    ("output", 5),
    ("use", 6),
    ("connect", 7),
    ("raster", 8),
    ("compute", 9),
    ("copy", 10),
    ("shader", 11),
    ("image", 12),
    ("buffer", 13),
    ("dot", 14)
  ]
