# Generated by tools/gen_tags.nim from ../doc/tags.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    PassTagId
    ModuleTagId
    StmtsTagId
    InputTagId
    OutputTagId
    UseTagId
    ConnectTagId
    ExternalTagId
    PresentTagId
    RasterTagId
    ComputeTagId
    CopyTagId
    ShaderTagId
    UsageTagId
    ImageTagId
    BufferTagId
    DotTagId
    ColorTagId

const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("pass", 1),
    ("module", 2),
    ("stmts", 3),
    ("input", 4),
    ("output", 5),
    ("use", 6),
    ("connect", 7),
    ("external", 8),
    ("present", 9),
    ("raster", 10),
    ("compute", 11),
    ("copy", 12),
    ("shader", 13),
    ("usage", 14),
    ("image", 15),
    ("buffer", 16),
    ("dot", 17),
    ("color", 18)
  ]
