## This tool generates the `rgc` tag enums from `doc/tags.md`.

import std/[os, sets, strutils]

proc toNimName(s: string; suffix: string): string =
  s[0].toUpperAscii & s.substr(1) & suffix

type
  EnumList = enum
    RgcStmt
    RgcType
    RgcExpr

proc toSuffix(e: EnumList): (string, string) =
  case e
  of RgcStmt: ("S", "NoStmt")
  of RgcType: ("T", "NoType")
  of RgcExpr: ("E", "NoExpr")

proc shortcutToEnumList(shortcut: string): EnumList =
  try:
    parseEnum[EnumList](shortcut.strip())
  except ValueError:
    quit "unknown enum type: " & shortcut

type
  EnumField = object
    name: string
    tag: string
    value: int
    desc: string

  EnumImpls = array[EnumList, seq[EnumField]]

const ToolPath = currentSourcePath()

proc writeClassifier(f: File; e: EnumList; fields: seq[EnumField]) =
  var first = ""
  var last = ""
  var prev = -1
  var holes: seq[int] = @[]
  for field in fields:
    if first.len == 0:
      first = field.tag
    last = field.tag
    if prev >= 0 and field.value != prev + 1:
      for h in prev + 1 .. field.value - 1:
        holes.add h
    prev = field.value

  f.write "\n\nproc rawTagIs" & $e & "*(raw: TagEnum): bool {.inline.} ="
  if holes.len <= 3:
    f.write "\n  raw >= " & toNimName(first, "TagId") & " and raw <= " & toNimName(last, "TagId")
    for h in holes:
      f.write " and raw != TagEnum(" & $h & ")"
    f.write "\n"
  else:
    f.write "\n  raw in {"
    for i, field in fields:
      if i > 0:
        f.write ", "
      f.write toNimName(field.tag, "TagId")
    f.write "}\n"

proc writeModel(output: string; inputName: string; data: EnumImpls) =
  let rootDir = output.parentDir
  let inputDisplay = relativePath(inputName, rootDir)
  let toolDisplay = relativePath(ToolPath, rootDir)
  let f = open(output, fmWrite)
  f.writeLine "# Generated by " & toolDisplay & " from " & inputDisplay & ". DO NOT EDIT!"
  f.writeLine ""
  f.writeLine "import tags"

  for e in EnumList:
    f.write "\n" & "type"
    f.write "\n  " & $e & "* = enum"
    f.write "\n    " & toSuffix(e)[1]
    for field in data[e]:
      f.write "\n    " & field.name
      f.write " = (ord(" & toNimName(field.tag, "TagId") & "), " & escape(field.tag) & ")"
      if field.desc.len > 0:
        f.write "  ## " & field.desc
    writeClassifier(f, e, data[e])

  f.write "\n"
  f.close()

proc writeTagsFile(output: string; inputName: string; data: seq[(string, int)]) =
  let rootDir = output.parentDir
  let inputDisplay = relativePath(inputName, rootDir)
  let toolDisplay = relativePath(ToolPath, rootDir)
  let f = open(output, fmWrite)
  f.writeLine "# Generated by " & toolDisplay & " from " & inputDisplay & ". DO NOT EDIT!"
  f.writeLine ""
  f.writeLine "type"
  f.writeLine "  TagEnum* = enum"
  f.writeLine "    InvalidTagId"
  for d in data:
    f.writeLine "    " & toNimName(d[0], "TagId")
  f.writeLine ""
  f.writeLine "const"
  f.writeLine "  TagData*: array[TagEnum, (string, int)] = ["
  f.write "    (" & escape("InvalidTagId") & ", 0)"
  for d in data:
    f.write ",\n"
    f.write "    (" & escape(d[0]) & ", " & $d[1] & ")"
  f.writeLine "\n  ]"
  f.close()

proc extractTagName(s: string): string =
  var i = 0
  while i < s.len and s[i] == ' ':
    inc i
  if i < s.len and s[i] == '`':
    inc i
  if i < s.len and s[i] == '(':
    inc i
  if i < s.len and s[i] in IdentStartChars:
    let start = i
    while i < s.len and s[i] in IdentChars:
      inc i
    result = s.substr(start, i - 1)
  else:
    quit "Cannot extract tag name from: " & s

proc genTags(inputName, tagsOutput, modelOutput: string) =
  var inp = open(inputName, fmRead)
  defer:
    inp.close()

  var i = -2
  var enumDecls = default(EnumImpls)
  var tags: seq[(string, int)] = @[]
  var knownTags = initHashSet[string]()

  for line in lines(inp):
    inc i
    if i <= 0: continue # skip header
    if line.strip.len == 0: continue
    let parts = line.split("|")
    if parts.len < 4:
      quit "WRONG LINE: " & line
    let tagName = extractTagName(parts[1])
    if knownTags.containsOrIncl(tagName):
      quit "DUPLICATE TAG: " & tagName
    tags.add (tagName, i)

    let desc = parts[3].strip()
    let affectedEnums = parts[2].split(",")
    assert affectedEnums.len > 0
    for affected in affectedEnums:
      let e = shortcutToEnumList(affected)
      enumDecls[e].add EnumField(
        name: toNimName(tagName, toSuffix(e)[0]),
        tag: tagName,
        value: i,
        desc: desc
      )

  writeTagsFile(tagsOutput, inputName, tags)
  writeModel(modelOutput, inputName, enumDecls)

proc main =
  let rootDir = ToolPath.parentDir.parentDir
  let inputName = if paramCount() == 0: rootDir.parentDir / "doc" / "tags.md" else: paramStr(1)
  let tagsOutput = rootDir / "tags.nim"
  let modelOutput = rootDir / "model_tags.nim"
  genTags(inputName, tagsOutput, modelOutput)

main()
